author: Dr_MadMan
database: false
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: me.dr_madman.dwarvesvszombies.DwarvesVsZombies
name: MobsAndMiners
startup: postworld
version: '.1'
commands:
   info:
      description: Displays info about the game
      usage: /<command>
      permission: 
      permission-message: You don't have <permission>
   votestart:
      description: Vote to start the game
      usage: /<command>
      permission: 
      permission-message: You don't have <permission>
   kill:
      description: Instantly respawn
      usage: /<command>
      permission: dvz.kill
      permission-message: You don't have <permission>
   md:
      description: Instantly respawn
      usage: /<command>
      permission: 
      permission-message: You don't have <permission>
   dwarf:
      description: Gives the player a kit
      usage: /<command> [name] 
      permission: dvz.dwarfdistribute
      permission-message: You don't have <permission>
   zombie:
      description: Gives the player a kit
      usage: /<command> [name] 
      permission: dvz.dwarfdistribute
      permission-message: You don't have <permission>
   start:
      description: Gives the player a kit
      usage: /<command> [name] 
      permission: dvz.dwarfdistribute
      permission-message: You don't have <permission>

















